"""Added file_id to image table

Revision ID: 1d040fbb74ce
Revises: 8c2a92134271
Create Date: 2023-11-04 03:35:28.011123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d040fbb74ce'
down_revision: Union[str, None] = '8c2a92134271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('file_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'file_id')
    # ### end Alembic commands ###
