"""Added timestamp and posted

Revision ID: 2af6a0df717b
Revises: 1d040fbb74ce
Create Date: 2023-11-04 04:09:12.689628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af6a0df717b'
down_revision: Union[str, None] = '1d040fbb74ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
