"""Added spoiler to photo

Revision ID: c9872bd4d4b5
Revises: f0ed48a3ded3
Create Date: 2023-11-15 23:38:03.886970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9872bd4d4b5'
down_revision: Union[str, None] = 'f0ed48a3ded3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('has_spoiler', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'has_spoiler')
    # ### end Alembic commands ###
