"""Added posted

Revision ID: f0ed48a3ded3
Revises: 2af6a0df717b
Create Date: 2023-11-04 04:12:46.479474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ed48a3ded3'
down_revision: Union[str, None] = '2af6a0df717b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('posted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'posted')
    # ### end Alembic commands ###
